payment.create:
  path: /payment
  methods: POST
  controller: App\Controller\PaymentController::create

payment.get:
  path: /payment/{id}
  methods: GET
  controller: App\Controller\PaymentController::getOne
