payment.create:
  path: /payment
  methods: POST
  controller: App\Controller\PaymentController::create

payment.get:
  path: /payment/{id}
  methods: GET
  controller: App\Controller\PaymentController::getOne

payment.getAll:
  path: /payments
  methods: GET
  controller: App\Controller\PaymentController::getAll

payment.delete:
  path: /payment/{id}
  methods: DELETE
  controller: App\Controller\PaymentController::delete

